# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13420062128c52d2f44e9a0b6c53d113322ac204518cd90fcd8b8500e0979451632ed1d47d8d223009eac87800cb75d79326df0938ac8ad2d3f61d9c825180b2

test:
  secret_key_base: 72c213ffcffa778bc4454a52608b43cbdb32307654813cf230a6ae321c7ec67727b56cee8bd142752d07445a34792f7fa65eb739600589147fc2386e7bff0df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
